export const SEARCH_URL = 'https://front-test.beta.aviasales.ru/search'
export const TICKETS_URL =
	'https://front-test.beta.aviasales.ru/tickets?searchId'
export const FETCH_REQUEST_TICKETS = 'FETCH_REQUEST_TICKETS'
export const FETCH_RECEIVE_TICKETS = 'FETCH_RECEIVE_TICKETS'
export const FETCH_FAILURE_TICKETS = 'FETCH_FAILURE_TICKETS'
export const FILTER = 'FILTER'
export const FASTEST = 'FASTEST'
export const CHEAPEST = 'CHEAPEST'
export const ALL = 'Все'
export const NO_STOPS = 'Без пересадок'
export const ONE_STOP = '1 пересадка'
export const TWO_STOPS = '2 пересадки'
export const THREE_STOPS = '3 пересадки'
export const COUNTER = 'COUNTER'
export const DEPARTURE = 'DEPARTURE'
export const ARRIVAL = 'ARRIVAL'
